# Generated by Django 4.1.3 on 2022-12-17 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0016_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
