# Generated by Django 4.1.3 on 2022-12-17 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0018_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ManyToManyField(related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
