# Generated by Django 4.1.3 on 2022-12-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0023_alter_comment_name_remove_comment_user_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
