# Generated by Django 4.1.3 on 2022-12-19 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0024_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(related_name='blog_subscribed', to=settings.AUTH_USER_MODEL),
        ),
    ]
